export const ADD_ARTICLE = "ADD_ARTICLE";
export const UPDATE_WALL_SIZE = "UPDATE_WALL_SIZE";
export const UPDATE_MAZE_WIDTH = "UPDATE_MAZE_WIDTH";
export const UPDATE_MAZE_HEIGHT = "UPDATE_MAZE_HEIGHT";
export const UPDATE_MAZE = "UPDATE_MAZE";
