export const UPDATE_WALL_SIZE = "UPDATE_WALL_SIZE";
export const UPDATE_MAZE_WIDTH = "UPDATE_MAZE_WIDTH";
export const UPDATE_MAZE_HEIGHT = "UPDATE_MAZE_HEIGHT";
export const UPDATE_MAZE = "UPDATE_MAZE";
export const UPDATE_ABSTRACT = "UPDATE_ABSTRACT";
export const UPDATE_ABSTRACT_PIXEL_SIZE = "UPDATE_ABSTRACT_PIXEL_SIZE";
export const UPDATE_ABSTRACT_WIDTH = "UPDATE_ABSTRACT_WIDTH";
export const UPDATE_ABSTRACT_HEIGHT = "UPDATE_ABSTRACT_HEIGHT";
